import:
    com.camden.skriptutils.YAML

on load:
    set {_level_name} to "default"
    set {_yaml_name} to join {_level_name} and ".yaml"

    set {_dict} to YAML.load({_yaml_name})
    
    {_dict}.put("status", null)
    clear {_players::*} 
    {_dict}.put("players", {_players::*})
    set {_serialized} to {_dict}.serialize()

    set {level::%{_level_name}%::metadata} to {_serialized}
    broadcast "%{level::%{_level_name}%::metadata}%"
